### ISSUE TITLE
Adapt to missing-Saturday data

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/flu-hosp-forecast#25]
- [x] For quantile forecasting: we probably just need to adjust the aheads on our forecasters (+ use the "latency bugfix" due to the cadence change).
- [x] For categorical trend forecasting: we already needed to adjust the current code for calculating the 7-day sum from which the deltas are calculated, the aheads, thresholds, and labeling; we would just do the first and second things slightly differently.

Specifically, friday is the target, and we're averaging Saturday-Friday

**Comment by dshemetov** [comment]
fixed by #31
