### ISSUE TITLE
Categorical rate definition changing again

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/flu-hosp-forecast#37]
> We must update our influenza categorical rate-trend target definition: we need to calculate deltas against a different week, and shift some of the rate thresholds used to different horizons.

>    I don't know when this should take effect though.  Possibly our next Wed forecast.

Categorical rate-trend interpretation table: an example of the relationship between dates and data for the rate trend target with a reference date of November 18, 2023. Corresponding target end dates, the dates included in the predicted EW, and the dates corresponding to the baseline EW. The rate trend target describes differences in the hospitalization rate between the baseline EW (one week prior to the EW of the reference date) and the target EW.

reference_date | horizon | target_end_date | target EW | target EW dates covered | baseline EW | baseline EW dates covered
-- | -- | -- | -- | -- | -- | --
2023-11-18 | 0 | 2023-11-18 | 46 | 2023-11-12 to 2023-11-18 | 45 | 2023-11-05 to 2023-11-11
2023-11-18 | 1 | 2023-11-25 | 47 | 2023-11-19 to 2023-11-25 | 45 | 2023-11-05 to 2023-11-11
2023-11-18 | 2 | 2023-12-02 | 48 | 2023-11-26 to 2023-12-02 | 45 | 2023-11-05 to 2023-11-11
2023-11-18 | 3 | 2023-12-09 | 49 | 2023-12-03 to 2023-12-09 | 45 | 2023-11-05 to 2023-11-11
-- | -- | -- | -- | -- | -- | --

**Comment by dsweber2** [comment]
@brookslogan @dshemetov @nmdefries we should probably decide who's doing this sooner rather than later, since it should happen before Wednesday

**Comment by dshemetov** [comment]
These changes don't sound hard. I can look into them on Monday.
